var test_stimuli = [
    { stimulus: { cue: "../img/226.png", targetA: "../img/621.png", targetB: "../img/386.png" } },
    { stimulus: { cue: "../img/599.png", targetA: "../img/480.png", targetB: "../img/97.png" } },
    { stimulus: { cue: "../img/434.png", targetA: "../img/580.png", targetB: "../img/336.png" } },
    { stimulus: { cue: "../img/544.png", targetA: "../img/669.png", targetB: "../img/434.png" } },
    { stimulus: { cue: "../img/68.png", targetA: "../img/408.png", targetB: "../img/78.png" } },
    { stimulus: { cue: "../img/68.png", targetA: "../img/235.png", targetB: "../img/196.png" } },
    { stimulus: { cue: "../img/68.png", targetA: "../img/654.png", targetB: "../img/426.png" } },
    { stimulus: { cue: "../img/68.png", targetA: "../img/663.png", targetB: "../img/367.png" } },
    { stimulus: { cue: "../img/68.png", targetA: "../img/69.png", targetB: "../img/78.png" } },
    { stimulus: { cue: "../img/68.png", targetA: "../img/622.png", targetB: "../img/453.png" } },
    { stimulus: { cue: "../img/408.png", targetA: "../img/235.png", targetB: "../img/426.png" } },
    { stimulus: { cue: "../img/408.png", targetA: "../img/663.png", targetB: "../img/359.png" } },
    { stimulus: { cue: "../img/408.png", targetA: "../img/69.png", targetB: "../img/367.png" } },
    { stimulus: { cue: "../img/408.png", targetA: "../img/622.png", targetB: "../img/391.png" } },
    { stimulus: { cue: "../img/235.png", targetA: "../img/654.png", targetB: "../img/192.png" } },
    { stimulus: { cue: "../img/235.png", targetA: "../img/663.png", targetB: "../img/473.png" } },
    { stimulus: { cue: "../img/235.png", targetA: "../img/69.png", targetB: "../img/216.png" } },
    { stimulus: { cue: "../img/235.png", targetA: "../img/622.png", targetB: "../img/426.png" } },
    { stimulus: { cue: "../img/654.png", targetA: "../img/663.png", targetB: "../img/227.png" } },
    { stimulus: { cue: "../img/654.png", targetA: "../img/69.png", targetB: "../img/336.png" } },
    { stimulus: { cue: "../img/663.png", targetA: "../img/69.png", targetB: "../img/64.png" } },
    { stimulus: { cue: "../img/663.png", targetA: "../img/622.png", targetB: "../img/659.png" } },
    { stimulus: { cue: "../img/69.png", targetA: "../img/622.png", targetB: "../img/386.png" } },
    { stimulus: { cue: "../img/626.png", targetA: "../img/80.png", targetB: "../img/199.png" } },
    { stimulus: { cue: "../img/453.png", targetA: "../img/359.png", targetB: "../img/461.png" } },
    { stimulus: { cue: "../img/453.png", targetA: "../img/673.png", targetB: "../img/367.png" } },
    { stimulus: { cue: "../img/453.png", targetA: "../img/78.png", targetB: "../img/155.png" } },
    { stimulus: { cue: "../img/453.png", targetA: "../img/590.png", targetB: "../img/64.png" } },
    { stimulus: { cue: "../img/453.png", targetA: "../img/216.png", targetB: "../img/663.png" } },
    { stimulus: { cue: "../img/453.png", targetA: "../img/564.png", targetB: "../img/546.png" } },
    { stimulus: { cue: "../img/453.png", targetA: "../img/336.png", targetB: "../img/654.png" } },
    { stimulus: { cue: "../img/453.png", targetA: "../img/357.png", targetB: "../img/680.png" } },
    { stimulus: { cue: "../img/453.png", targetA: "../img/46.png", targetB: "../img/461.png" } },
    { stimulus: { cue: "../img/359.png", targetA: "../img/78.png", targetB: "../img/654.png" } },
    { stimulus: { cue: "../img/359.png", targetA: "../img/590.png", targetB: "../img/68.png" } },
    { stimulus: { cue: "../img/359.png", targetA: "../img/216.png", targetB: "../img/556.png" } },
    { stimulus: { cue: "../img/359.png", targetA: "../img/426.png", targetB: "../img/235.png" } },
    { stimulus: { cue: "../img/359.png", targetA: "../img/564.png", targetB: "../img/391.png" } },
    { stimulus: { cue: "../img/359.png", targetA: "../img/653.png", targetB: "../img/556.png" } },
    { stimulus: { cue: "../img/359.png", targetA: "../img/336.png", targetB: "../img/64.png" } },
    { stimulus: { cue: "../img/359.png", targetA: "../img/46.png", targetB: "../img/367.png" } },
    { stimulus: { cue: "../img/673.png", targetA: "../img/78.png", targetB: "../img/659.png" } },
    { stimulus: { cue: "../img/673.png", targetA: "../img/653.png", targetB: "../img/556.png" } },
    { stimulus: { cue: "../img/673.png", targetA: "../img/122.png", targetB: "../img/235.png" } },
    { stimulus: { cue: "../img/673.png", targetA: "../img/336.png", targetB: "../img/721.png" } },
    { stimulus: { cue: "../img/78.png", targetA: "../img/216.png", targetB: "../img/68.png" } },
    { stimulus: { cue: "../img/78.png", targetA: "../img/653.png", targetB: "../img/358.png" } },
    { stimulus: { cue: "../img/78.png", targetA: "../img/564.png", targetB: "../img/235.png" } },
    { stimulus: { cue: "../img/78.png", targetA: "../img/336.png", targetB: "../img/725.png" } },
    { stimulus: { cue: "../img/78.png", targetA: "../img/301.png", targetB: "../img/473.png" } },
    { stimulus: { cue: "../img/590.png", targetA: "../img/216.png", targetB: "../img/654.png" } },
    { stimulus: { cue: "../img/590.png", targetA: "../img/122.png", targetB: "../img/64.png" } },
    { stimulus: { cue: "../img/590.png", targetA: "../img/566.png", targetB: "../img/166.png" } },
    { stimulus: { cue: "../img/590.png", targetA: "../img/46.png", targetB: "../img/654.png" } },
    { stimulus: { cue: "../img/216.png", targetA: "../img/653.png", targetB: "../img/663.png" } },
    { stimulus: { cue: "../img/216.png", targetA: "../img/566.png", targetB: "../img/659.png" } },
    { stimulus: { cue: "../img/216.png", targetA: "../img/336.png", targetB: "../img/663.png" } },
    { stimulus: { cue: "../img/216.png", targetA: "../img/357.png", targetB: "../img/64.png" } },
    { stimulus: { cue: "../img/426.png", targetA: "../img/653.png", targetB: "../img/556.png" } },
    { stimulus: { cue: "../img/564.png", targetA: "../img/122.png", targetB: "../img/654.png" } },
    { stimulus: { cue: "../img/653.png", targetA: "../img/122.png", targetB: "../img/721.png" } },
    { stimulus: { cue: "../img/653.png", targetA: "../img/566.png", targetB: "../img/447.png" } },
    { stimulus: { cue: "../img/653.png", targetA: "../img/301.png", targetB: "../img/57.png" } },
    { stimulus: { cue: "../img/653.png", targetA: "../img/357.png", targetB: "../img/619.png" } },
    { stimulus: { cue: "../img/653.png", targetA: "../img/46.png", targetB: "../img/447.png" } },
    { stimulus: { cue: "../img/122.png", targetA: "../img/566.png", targetB: "../img/626.png" } },
    { stimulus: { cue: "../img/122.png", targetA: "../img/301.png", targetB: "../img/359.png" } },
    { stimulus: { cue: "../img/122.png", targetA: "../img/357.png", targetB: "../img/461.png" } },
    { stimulus: { cue: "../img/166.png", targetA: "../img/155.png", targetB: "../img/657.png" } },
    { stimulus: { cue: "../img/166.png", targetA: "../img/386.png", targetB: "../img/654.png" } },
    { stimulus: { cue: "../img/64.png", targetA: "../img/155.png", targetB: "../img/359.png" } },
    { stimulus: { cue: "../img/64.png", targetA: "../img/386.png", targetB: "../img/426.png" } },
    { stimulus: { cue: "../img/64.png", targetA: "../img/587.png", targetB: "../img/68.png" } },
    { stimulus: { cue: "../img/64.png", targetA: "../img/556.png", targetB: "../img/336.png" } },
    { stimulus: { cue: "../img/569.png", targetA: "../img/386.png", targetB: "../img/659.png" } },
    { stimulus: { cue: "../img/569.png", targetA: "../img/447.png", targetB: "../img/357.png" } },
    { stimulus: { cue: "../img/569.png", targetA: "../img/587.png", targetB: "../img/336.png" } },
    { stimulus: { cue: "../img/569.png", targetA: "../img/556.png", targetB: "../img/721.png" } },
    { stimulus: { cue: "../img/155.png", targetA: "../img/447.png", targetB: "../img/426.png" } },
    { stimulus: { cue: "../img/155.png", targetA: "../img/587.png", targetB: "../img/74.png" } },
    { stimulus: { cue: "../img/386.png", targetA: "../img/447.png", targetB: "../img/721.png" } },
    { stimulus: { cue: "../img/386.png", targetA: "../img/587.png", targetB: "../img/391.png" } },
    { stimulus: { cue: "../img/386.png", targetA: "../img/556.png", targetB: "../img/357.png" } },
    { stimulus: { cue: "../img/447.png", targetA: "../img/587.png", targetB: "../img/199.png" } },
    { stimulus: { cue: "../img/447.png", targetA: "../img/556.png", targetB: "../img/78.png" } },
    { stimulus: { cue: "../img/587.png", targetA: "../img/556.png", targetB: "../img/359.png" } },
    { stimulus: { cue: "../img/15.png", targetA: "../img/579.png", targetB: "../img/549.png" } },
    { stimulus: { cue: "../img/517.png", targetA: "../img/718.png", targetB: "../img/68.png" } },
    { stimulus: { cue: "../img/517.png", targetA: "../img/199.png", targetB: "../img/336.png" } },
    { stimulus: { cue: "../img/549.png", targetA: "../img/164.png", targetB: "../img/473.png" } },
    { stimulus: { cue: "../img/549.png", targetA: "../img/199.png", targetB: "../img/166.png" } },
    { stimulus: { cue: "../img/164.png", targetA: "../img/199.png", targetB: "../img/359.png" } },
    { stimulus: { cue: "../img/164.png", targetA: "../img/628.png", targetB: "../img/357.png" } },
    { stimulus: { cue: "../img/164.png", targetA: "../img/165.png", targetB: "../img/447.png" } },
    { stimulus: { cue: "../img/718.png", targetA: "../img/523.png", targetB: "../img/663.png" } },
    { stimulus: { cue: "../img/718.png", targetA: "../img/391.png", targetB: "../img/654.png" } },
    { stimulus: { cue: "../img/199.png", targetA: "../img/523.png", targetB: "../img/166.png" } },
    { stimulus: { cue: "../img/628.png", targetA: "../img/523.png", targetB: "../img/155.png" } },
    { stimulus: { cue: "../img/165.png", targetA: "../img/391.png", targetB: "../img/122.png" } },
    { stimulus: { cue: "../img/67.png", targetA: "../img/680.png", targetB: "../img/68.png" } },
    { stimulus: { cue: "../img/110.png", targetA: "../img/680.png", targetB: "../img/721.png" } },
    { stimulus: { cue: "../img/268.png", targetA: "../img/91.png", targetB: "../img/166.png" } },
    { stimulus: { cue: "../img/268.png", targetA: "../img/680.png", targetB: "../img/659.png" } },
    { stimulus: { cue: "../img/91.png", targetA: "../img/680.png", targetB: "../img/386.png" } },
    { stimulus: { cue: "../img/619.png", targetA: "../img/81.png", targetB: "../img/721.png" } },
    { stimulus: { cue: "../img/192.png", targetA: "../img/461.png", targetB: "../img/359.png" } },
    { stimulus: { cue: "../img/192.png", targetA: "../img/473.png", targetB: "../img/122.png" } },
    { stimulus: { cue: "../img/192.png", targetA: "../img/97.png", targetB: "../img/68.png" } },
    { stimulus: { cue: "../img/461.png", targetA: "../img/97.png", targetB: "../img/556.png" } },
    { stimulus: { cue: "../img/367.png", targetA: "../img/473.png", targetB: "../img/336.png" } },
    { stimulus: { cue: "../img/367.png", targetA: "../img/97.png", targetB: "../img/663.png" } },
    { stimulus: { cue: "../img/367.png", targetA: "../img/264.png", targetB: "../img/155.png" } },
    { stimulus: { cue: "../img/473.png", targetA: "../img/97.png", targetB: "../img/199.png" } },
    { stimulus: { cue: "../img/97.png", targetA: "../img/264.png", targetB: "../img/64.png" } },
    { stimulus: { cue: "../img/295.png", targetA: "../img/340.png", targetB: "../img/357.png" } },
    { stimulus: { cue: "../img/295.png", targetA: "../img/278.png", targetB: "../img/317.png" } }
];

var instructionsPicturesEN = ['<h3>Welcome</h3>' +
    '<p>This experiment is about picture relatednesss.</p>' +
    '<p>In this experiment,  a fixation cross followed by three pictures will appear in the middle of the screen. ' +
    '<p>For example:</p><p><img src="../img/examplePictures.png" width="220px"></p>' +
    '<br>Press <strong>f</strong> if the left picture is in any way more related to the bottom word. ' +
    '<br>Press <strong>j</strong> if the right picture is in any way related to the bottom word.</p>' +
    '<p>Try to respond as <strong>quickly as possible</strong>.</p>' +
    '<p>Pictures might occur repeatedly, some combinations are harder than others, but follow your intuition.' +
    '<p>There are 116 trials in this study and the task is about 10 minutes.</p><p>Click next to begin.</p>'
];


var instructionsNext = 'Next';
var instructionsPrevious = 'Previous';

var imageList = [
    "../img/226.png", "../img/599.png", "../img/434.png", "../img/544.png", "../img/68.png",
    "../img/408.png", "../img/235.png", "../img/654.png", "../img/663.png", "../img/69.png",
    "../img/626.png", "../img/453.png", "../img/359.png", "../img/673.png", "../img/78.png",
    "../img/590.png", "../img/216.png", "../img/426.png", "../img/564.png", "../img/653.png",
    "../img/122.png", "../img/166.png", "../img/64.png", "../img/569.png", "../img/155.png",
    "../img/386.png", "../img/447.png", "../img/587.png", "../img/15.png", "../img/517.png",
    "../img/549.png", "../img/164.png", "../img/718.png", "../img/199.png", "../img/628.png",
    "../img/165.png", "../img/67.png", "../img/110.png", "../img/268.png", "../img/91.png",
    "../img/619.png", "../img/192.png", "../img/461.png", "../img/367.png", "../img/473.png",
    "../img/97.png", "../img/295.png", "../img/621.png", "../img/480.png", "../img/580.png",
    "../img/669.png", "../img/622.png", "../img/80.png", "../img/336.png", "../img/357.png",
    "../img/46.png", "../img/301.png", "../img/566.png", "../img/556.png", "../img/579.png",
    "../img/523.png", "../img/391.png", "../img/680.png", "../img/81.png", "../img/264.png",
    "../img/340.png", "../img/278.png", "../img/196.png", "../img/227.png", "../img/659.png",
    "../img/546.png", "../img/721.png", "../img/358.png", "../img/725.png", "../img/57.png",
    "../img/657.png", "../img/74.png", "../img/317.png",
];